### PR TITLE
fix(arcjet-node): Wrap `process.env` access with a getter object

### LINKED ISSUE #2986: Unable to access NODE_ENV or ARCJET_ENV from Gatsby
If you use Arcjet within a Gatsby function, the Arcjet client does not pick up any environment variables. 

This means that when running locally, it will always log the `✦Aj WARN Client IP address is missing. If this is a dev environment set the ARCJET_ENV env var to "development"` warning and fail to build the characteristics with `✦Aj ERROR Failed to build fingerprint. Please verify your Characteristics.` because it can't find a valid IP address.

I am able to access the environment variables from within the function so I can set `process.env.ARCJET_KEY` with a normal instantiation of the client. I tried placing the client inside and outside of the handler, but it still seems unable to detect the environment variables. A `console.log` shows they are all set.

As a workaround I can hard code the local IP if we detect we're in development:

```ts
const ip = process.env.NODE_ENV === 'development' ? '1.1.1.1' : undefined;
const decision = await aj.protect(ip ? { ...req, socket: { remoteAddress: ip } } : req);
```

Here's a simple Gatsby function demonstrating the issue. It can be placed in `src/api/arcjet.ts` to be accessed from `http://localhost:8000/api/arcjet`

```ts
import arcjet, { slidingWindow } from "@arcjet/node";
import type { GatsbyFunctionRequest, GatsbyFunctionResponse } from 'gatsby';

const aj = arcjet({
    key: process.env.ARCJET_KEY!,
    rules: [
        slidingWindow({
            mode: "LIVE",
            interval: "10m",
            max: 500,
        }),
    ],
});

const handler = async (
    req: GatsbyFunctionRequest,
    res: GatsbyFunctionResponse
) => {
    const decision = await aj.protect(req);
    console.log("IP Address", req.socket.remoteAddress);
    console.log("Arcjet ENV", process.env.ARCJET_ENV);

    return res.json({ arcjet: decision });
}


export default handler;
```

The output is:

```
warn ✦Aj WARN Client IP address is missing. If this is a dev environment set the ARCJET_ENV env var to "development"
Executed function "/api/arcjet" in 5ms

 ERROR  UNKNOWN

✦Aj ERROR Failed to build fingerprint. Please verify your Characteristics.
      error: {}

IP Address ::1
Arcjet ENV development
```

### PR DESCRIPTION
**Pull request by blaine-arcjet**
Closes #2986

This adds an abstraction over `process.env` in the Arcjet Node adapter. This is necessary because Gatsby uses Webpack with the replacer plugin to replace `process.env.SOMEVAR` with the string literal of the environment variable. However, we still want to support environment modification in proper Node.js runtime environments.

We may want to apply this same technique to all adapters but it is fragile so I erred on the side of caution.

### CODE REVIEW

File: examples/gatsby-rate-limit/src/pages/index.tsx [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+    } else {
+      setError("");
+    }
+  }
+  return (
+    <main style={pageStyles}>
+      <button onClick={onClick}>Get Message</button>
+      <div>{message ? `message: ${message}` : null}</div>
+      <div>{error ? `error: ${error}` : null}</div>
+      <h1 style={headingStyles}>
```
Comment (davidmytton) [inline examples/gatsby-rate-limit/src/pages/index.tsx:162]: We can probably remove everything from here on down.

**Review by davidmytton — APPROVED** [review]

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/@babel/plugin-proposal-class-properties@7.18.6
@SocketSecurity ignore npm/@babel/plugin-proposal-nullish-coalescing-operator@7.18.6
@SocketSecurity ignore npm/@babel/plugin-proposal-numeric-separator@7.18.6
@SocketSecurity ignore npm/@babel/plugin-proposal-object-rest-spread@7.20.7
@SocketSecurity ignore npm/@babel/plugin-proposal-optional-chaining@7.21.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/sharp@0.32.6
@SocketSecurity ignore npm/v8-compile-cache@2.4.0
@SocketSecurity ignore npm/@babel/plugin-syntax-numeric-separator@7.10.4
@SocketSecurity ignore npm/fb-watchman@2.0.2
@SocketSecurity ignore npm/kind-of@6.0.3
@SocketSecurity ignore npm/got@11.8.6
@SocketSecurity ignore npm/open@7.4.2
@SocketSecurity ignore npm/at-least-node@1.0.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/cacheable-lookup@5.0.4
@SocketSecurity ignore npm/cacheable-request@7.0.4
@SocketSecurity ignore npm/http2-wrapper@1.0.3
@SocketSecurity ignore npm/responselike@2.0.1
@SocketSecurity ignore npm/clone-response@1.0.3
@SocketSecurity ignore npm/resolve-alpn@1.2.1
@SocketSecurity ignore npm/is-promise@2.2.2
@SocketSecurity ignore npm/stack-trace@0.0.10
@SocketSecurity ignore npm/set-blocking@2.0.0
@SocketSecurity ignore npm/strip-ansi@3.0.1
@SocketSecurity ignore npm/ansi-regex@2.1.1
@SocketSecurity ignore npm/which-module@2.0.1
@SocketSecurity ignore npm/@hapi/topo@5.1.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/@sideway/formula@3.0.1
@SocketSecurity ignore npm/address@1.2.2
@SocketSecurity ignore npm/babel-plugin-syntax-trailing-function-commas@7.0.0-beta.0
@SocketSecurity ignore npm/babel-preset-fbjs@3.4.0
@SocketSecurity ignore npm/better-opn@2.1.1
@SocketSecurity ignore npm/@sideway/address@4.1.5
@SocketSecurity ignore npm/boolbase@1.0.0
@SocketSecurity ignore npm/command-exists@1.2.9
@SocketSecurity ignore npm/cosmiconfig@7.1.0
@SocketSecurity ignore npm/domutils@2.8.0
@SocketSecurity ignore npm/error-stack-parser@2.1.4
@SocketSecurity ignore npm/htmlparser2@6.1.0
@SocketSecurity ignore npm/is-extglob@1.0.0
@SocketSecurity ignore npm/hosted-git-info@3.0.8
@SocketSecurity ignore npm/sudo-prompt@8.2.5

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/unicode-match-property-ecmascript@2.0.0
    @SocketSecurity ignore npm/event-source-polyfill@1.0.31
    @SocketSecurity ignore npm/babel-eslint@10.1.0
    @SocketSecurity ignore npm/parse-filepath@1.0.2
    @SocketSecurity ignore npm/@ardatan/relay-compiler@12.0.0
    @SocketSecurity ignore npm/@nicolo-ribaudo/eslint-scope-5-internals@5.1.1-v1
    @SocketSecurity ignore npm/is-relative@1.0.0
    @SocketSecurity ignore npm/is-unc-path@1.0.0
    @SocketSecurity ignore npm/unc-path-regex@0.1.2
    @SocketSecurity ignore npm/@types/mkdirp@0.5.2
    @SocketSecurity ignore npm/xmlhttprequest-ssl@2.0.0
    @SocketSecurity ignore npm/config-chain@1.1.13
    @SocketSecurity ignore npm/stable@0.1.8
    @SocketSecurity ignore npm/strict-uri-encode@2.0.0
    @SocketSecurity ignore npm/detect-port-alt@1.1.6
    @SocketSecurity ignore npm/recursive-readdir@2.2.3
    @SocketSecurity ignore npm/json-loader@0.5.7
    @SocketSecurity ignore npm/cacheable-lookup@7.0.0
    @SocketSecurity ignore npm/express-http-proxy@1.6.3
    @SocketSecurity ignore npm/physical-cpu-count@2.0.0
    @SocketSecurity ignore npm/@types/rimraf@2.0.5
    @SocketSecurity ignore npm/@parcel/package-manager@2.8.3
    @SocketSecurity ignore npm/@parcel/reporter-dev-server@2.8.3
    @SocketSecurity ignore npm/@parcel/workers@2.8.3
    @SocketSecurity ignore npm/lmdb@2.5.2
    @SocketSecurity ignore npm/@vercel/webpack-asset-relocator-loader@1.7.3
    @SocketSecurity ignore npm/devcert@1.2.2
    @SocketSecurity ignore npm/lmdb@2.5.3
    @SocketSecurity ignore npm/socket.io@4.7.1
    @SocketSecurity ignore npm/string-similarity@1.2.2
    @SocketSecurity ignore npm/get-stream@8.0.1
    @SocketSecurity ignore npm/is64bit@2.0.0
    @SocketSecurity ignore npm/http2-wrapper@2.2.1
    @SocketSecurity ignore npm/moment@2.30.1
    @SocketSecurity ignore npm/es5-ext@0.10.64
    @SocketSecurity ignore npm/detect-port@1.6.1
    @SocketSecurity ignore npm/msgpackr-extract@3.0.3
    @SocketSecurity ignore npm/engine.io@6.5.5
    @SocketSecurity ignore npm/envinfo@7.14.0
    @SocketSecurity ignore npm/babel-plugin-remove-graphql-queries@5.14.0
    @SocketSecurity ignore npm/babel-preset-gatsby@3.14.0
    @SocketSecurity ignore npm/gatsby-cli@5.14.0
    @SocketSecurity ignore npm/gatsby-core-utils@4.14.0
    @SocketSecurity ignore npm/gatsby-graphiql-explorer@3.14.0
    @SocketSecurity ignore npm/gatsby-legacy-polyfills@3.14.0
    @SocketSecurity ignore npm/gatsby-page-utils@3.14.0
    @SocketSecurity ignore npm/gatsby-parcel-config@1.14.0
    @SocketSecurity ignore npm/gatsby-plugin-page-creator@5.14.0
    @SocketSecurity ignore npm/gatsby-plugin-typescript@5.14.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/open@8.4.2
    @SocketSecurity ignore npm/gatsby-plugin-utils@4.14.0
    @SocketSecurity ignore npm/gatsby-react-router-scroll@6.14.0
    @SocketSecurity ignore npm/gatsby-script@2.14.0
    @SocketSecurity ignore npm/gatsby-worker@2.14.0
    @SocketSecurity ignore npm/gatsby-sharp@1.14.0
    @SocketSecurity ignore npm/create-gatsby@3.14.0
    @SocketSecurity ignore npm/@gatsbyjs/parcel-namer-relative-to-cwd@2.14.0
    @SocketSecurity ignore npm/graphql-http@1.22.4
    @SocketSecurity ignore npm/async-function@1.0.0
    @SocketSecurity ignore npm/react-error-overlay@6.1.0
    @SocketSecurity ignore npm/caniuse-lite@1.0.30001704
